MyNewTask/Models/Category.cs
using System;
using System.Collections.Generic;
// New Addition for Foreign key 
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyNewTask.Models
{
    public class Category
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

MyNewTask/Models/MarketDbcontext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyNewTask.Models
{
    public class MarketDBcontext : DbContext
    {
        public MarketDBcontext() 
            : base("name=MarketDBcontext")
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Category> Category { get; set; }

    }
}

MyNewTask/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyNewTask.Models
{
  public class Product
    {
        [Key]
        public int ID { get; set; }

        [Display(Name="Product Name")]
        public string Name { get; set; }

        [Display(Name = "Price")]
        public int? Price { get; set; }

        [Display(Name = "Quantity")]
        public int? Quantity { get; set; }

        [ForeignKey("Category")]
        [Required(ErrorMessage ="Category must be required field")]

        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
   
    
}

MyNewTask/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyNewTask.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyNewTask/Controllers/ShopController.cs
using MyNewTask.Models;
using MyNewTask.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyNewTask.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            MarketDBcontext db = new MarketDBcontext();
            var model = db.Product.ToList();

            return View(model);
        }       

        [HttpGet]
        public ActionResult ViewCategory()
        {
            MarketDBcontext db = new MarketDBcontext();
            var model = db.Category.ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult CreateCategory(int? id)
        {

            MarketDBcontext db = new MarketDBcontext();
            if (id.HasValue)
            {
                var model = db.Category.Find(id);               
                return View(model);
            }
           
            return View(); 
        }

        [HttpGet]
        public ActionResult DeleteCategory( int? id)
        {
            MarketDBcontext db = new MarketDBcontext();
            var model= db.Category.Find(id);

            return View(model);
        } 

        [HttpPost]
        public ActionResult DeleteCategory(int id)
        { 
            if (ModelState.IsValid)

            {
                MarketDBcontext db = new MarketDBcontext();
                var model = db.Category.Find(id);
                db.Category.Remove(model);             
                db.SaveChanges();
            }
                return RedirectToAction("ViewCategory");  
                           
        }

        [HttpPost]
        public ActionResult CreateCategory(int? id, Category model)
        {
            MarketDBcontext db = new MarketDBcontext();

            if (id.HasValue)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewCategory");
            }

            if (ModelState.IsValid)
            {
                db.Category.Add(model);
                db.SaveChanges();
                return RedirectToAction("ViewCategory");
            }

            return View(model);
        }


        [HttpGet]
        public ActionResult EditProduct(int? id)
        {
            MarketDBcontext db = new MarketDBcontext();

            Product productModel;
            if (id.HasValue)
            {
             productModel = db.Product.Find(id);
            //productModel = db.Product.Where(p => p.ID == id.Value).SingleOrDefault();
             ViewBag.CategorySelectList = new SelectList(db.Category.ToList(), "ID", "Name", productModel.CategoryId);
                return View(productModel);
            }            
            
            Product product = new Product();          
            
            ViewBag.CategorySelectList = new SelectList(db.Category.ToList(), "ID", "Name", product.CategoryId);
           
            return View(product);
        }

        [HttpPost]
        public ActionResult EditProduct(int? id, Product model)
        {
            MarketDBcontext db = new MarketDBcontext();
            if (id.HasValue)
            { 
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            if (ModelState.IsValid)
            {
                db.Product.Add(model);
                db.SaveChanges();
                return RedirectToAction("index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteProduct(int? id)
        {
            MarketDBcontext db = new MarketDBcontext();
         var model=db.Product.Find(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteProduct(int id)
        {
            MarketDBcontext db = new MarketDBcontext();
            Product product = db.Product.Find(id);
            db.Product.Remove(product);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

MyNewTask/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyNewTask/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyNewTask/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MyNewTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shoping WebSite", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create Category", "CreateCategory", "Shop")</li>
                    <li>@Html.ActionLink("Category List", "ViewCategory", "Shop")</li>
                    <li>@Html.ActionLink("Create Product", "EditProduct", "Shop")</li>
                    <li>@Html.ActionLink("Product list","Index","Shop")</li>
                   
                   
                   
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyNewTask/Views/Shop/CreateCategory.cshtml
@model MyNewTask.Models.Category
@{
    ViewBag.Title = "CreateCatergory";
}

<h2>Create Catergory</h2>
@using (Html.BeginForm("CreateCategory", "Shop", FormMethod.Post))
{
    @Html.TextBoxFor(m=>m.Name)
   

    <input type="submit" value="Submit">
}

MyNewTask/Views/Shop/CreateProduct.cshtml
@model MyNewTask.Models.Product
@{
    ViewBag.Title = "CreateProduct";
}
<h2>CreateProduct</h2>

@using (Html.BeginForm("CreateProduct", "Shop", FormMethod.Post))

{
    // @Html.HiddenFor(Model.CategoryId)
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>
    </div>
        <div class="form-horizontal">


            <div class="form-group">
                @Html.LabelFor(model => model.Category, new { @class = "contrl-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Name", "Please Select Category")
                    @*@Html.TextBoxFor(model => model.Quantity)
                        @Html.ValidationMessageFor(model => model.Quantity)*@
                </div>
            </div>
        <div class="form-group">

          <input type="submit" value="Submit">
            </div>
    </div>


    //   @Html.TextBoxFor(p => p.Name)
    //  @Html.TextBoxFor(s => s.Price)
    // @Html.TextBoxFor(o => o.Quantity)

}

MyNewTask/Views/Shop/DeleteCategory.cshtml
@model MyNewTask.Models.Category
@{
    ViewBag.Title = "DeleteCategory";
}

<h2>Are you sure you want to delete Category</h2>
@using (@Html.BeginForm("DeleteCategory", "Shop",FormMethod.Post))
{
    @Html.TextBoxFor(m => m.Name)
    
    <input type="submit" value="Submit" />

}

MyNewTask/Views/Shop/DeleteProduct.cshtml
@model MyNewTask.Models.Product
@{
    ViewBag.Title = "DeleteProduct";
}

<h2>Are you sure you want to <strong> Delete</strong>  Product</h2>
@using (@Html.BeginForm("DeleteProduct", "Shop", FormMethod.Post))

{

    @*<table class="table"> </table>*@

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "contrl-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayTextFor(m=>m.Category.Name)
                @*@Html.DropDownListFor(m => m.CategoryId, (SelectList)ViewBag.CategorySelectList, "Select...")*@
            </div>
        </div>

    </div>

<input  type="submit" value="Delete"   />
}

MyNewTask/Views/Shop/Edit.cshtml
@model MyNewTask.Models.Category
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@{
    ViewBag.Title = "CreateCatergory";
}

<h2>Create Catergory</h2>
@using (Html.BeginForm("CreateCategory", "Shop", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.Name)
    <input type="submit" value="Submit">
}

MyNewTask/Views/Shop/EditCategory.cshtml
@model MyNewTask.Models.Category
@{
    ViewBag.Title = "EditCategory";
}

<h2>EditCategory</h2>

@{
    ViewBag.Title = "CreateCatergory";
}

<h2>Create Catergory</h2>
@using (Html.BeginForm("EditCategory", "Shop", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.Name)
    <input type="submit" value="Submit">
}

MyNewTask/Views/Shop/EditProduct.cshtml
@model MyNewTask.Models.Product 
@{
    ViewBag.Title = "EditProduct";
} 
<h2>EditProduct</h2>
@using (Html.BeginForm("EditProduct", "Shop", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

            <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "contrl-label col-md-2" })            
            <div class="col-md-10">
                @Html.DropDownListFor(m=>m.CategoryId, (SelectList)ViewBag.CategorySelectList,"Select...")
            </div>
        </div>

    </div>
    <input type="submit" value="Submit">       

}

MyNewTask/Views/Shop/Index.cshtml
@model  IEnumerable<MyNewTask.Models.Product >
@{
    ViewBag.Title = "Index";
}

 <h2>List of Products</h2>
 <h4>@Html.ActionLink("Create New Catergory", "CreateCategory") </h4>
 <h4>@Html.ActionLink("Create New Product", "EditProduct") </h4>
 <h4>@Html.ActionLink("View Category", "ViewCategory") </h4>
 

<table class="table">
   <tr>       
       <th>Product Name </th>
       <th>Price</th>
       <th>Category</th>
       <th>Quantity</th> 
       <th>Edit Product</th>
   </tr>
@foreach(var item in Model)
{
   <tr>
       <td>
            @Html.DisplayFor(modelItem => item.Name)
       </td>
       <td> 
           Rs : @string.Format("{0:00}",@Html.DisplayFor(modelItem => item.Price))
           
       </td>
       <td>
            @Html.DisplayFor(modelItem=>item.Category.Name)
       </td>
       <td>
            @Html.DisplayFor(modelItem=>item.Quantity)
       </td>
       <td>
           @Html.ActionLink("Edit", "EditProduct", new { item.ID })
       </td>
       <td>
           @Html.ActionLink("Delete", "DeleteProduct", new { item.ID })
       </td>

  </tr>
}
</table>

MyNewTask/Views/Shop/ViewCategory.cshtml
@model IEnumerable <MyNewTask.Models.Category>
@{
    ViewBag.Title = "ViewCategory";
}
<h4>@Html.ActionLink("Create New Catergory", "CreateCategory") </h4>
<h4>@Html.ActionLink("Create New Product", "EditProduct") </h4>

<table class="table">
    <tr>
        @*<th>Number</th>*@
        <th>Category Type </th>
        <th>Edit Category</th>
        <th>Delete Category</th>
    </tr>
    @foreach (var item in Model) {
    <tr>       
        <td> @Html.DisplayFor(s=>item.Name)  </td>
        <td>@Html.ActionLink("Edit Category", "CreateCategory", new {id=item.ID}) </td>
        <td>@Html.ActionLink("Delete Category", "DeleteCategory", new {id=item.ID})</td>
    </tr>
    
    }

</table>